const allEmails = {
  receivedEmails: [],
  sentEmails: [],

  groups: [
    {
      id: 1,
      groupName: "Anitque Car",
      name: "Stephan",
      email: "Stephan@rclister.com",
      phone: "12345",
      country: "INDIA",
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      contact1Name: "Stephan Cuillerier",
      contact1Email: "stephan@rclister.com",
      contact1Phone: "12345",
      contact2Name: "Stephan Cuillerier",
      contact2Email: "stephan@rclister.com",
      contact2Phone: "12345",
    },
    {
      id: 2,
      groupName: "Anitque Car",
      name: "Stephan",
      email: "Stephan@rclister.com",
      date: "10 oct 2022",
      country: "INDIA",
      phone: "12345",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      contact1Name: "Stephan Cuillerier",
      contact1Email: "stephan@rclister.com",
      contact1Phone: "12345",
      contact2Name: "Stephan Cuillerier",
      contact2Email: "stephan@rclister.com",
      contact2Phone: "12345",
    },
    {
      id: 3,
      groupName: "Anitque Car",
      name: "Stephan",
      email: "Stephan@rclister.com",
      date: "10 oct 2022",
      registered: true,
      country: "",
      phone: "12345",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      contact1Name: "Stephan Cuillerier",
      contact1Email: "stephan@rclister.com",
      contact1Phone: "12345",
      contact2Name: "Stephan Cuillerier",
      contact2Email: "stephan@rclister.com",
      contact2Phone: "12345",
    },
  ],

  volunteers: [
    {
      id: 1,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 2,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 3,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      registered: true,
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 4,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 5,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      registered: true,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 6,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      registered: true,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
    {
      id: 7,
      volunteerName: "John Shane",
      email: "shane@rclister.com",
      date: "10 oct 2022",
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      country: "",
      phone: "12345678",
    },
  ],
  applications: [
    {
      id: 1,
      name: "John Sane",
      email: "john@rclister.com",
      acceptedDate: "10 oct 2022",
      applicationDate: "2022",
      approved: true,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      orgName: "ABC",
      groupPresident: "RFT",
      phone: "909090",
      representingCountry: true,
      countryName: "INDIA",
      haveWalkers: true,
      noOfWalkers: "5",
      bringingCar: true,
      noOfCars: "8",
      bringingSUV: true,
      noOfSUV: "5",
      bringingTruck: true,
      noOfTrucks: "1",
      brandOfTruck: "Any",
      trailersAttached: true,
      trailerLength: "5ft",
      bringingFloats: true,
      floatsLength: "4ft",
      isThereFireExtinguisher: "Yes",
      bringingAnimals: true,
      bringingHorses: true,
      areHorsesInsured: true,
      noOfHorses: "5",
      bringingDogs: true,
      noOfDogs: "4",
      anyOtherAnimal: true,
      anyOtherAnimalNoAndDescription: "Pigion, 5",
    },
    {
      id: 2,
      name: "John Sane",
      email: "john@rclister.com",
      acceptedDate: "10 oct 2022",
      applicationDate: "2022",
      approved: false,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      orgName: "ABC",
      groupPresident: "RFT",
      phone: "909090",
      representingCountry: true,
      countryName: "INDIA",
      haveWalkers: true,
      noOfWalkers: "5",
      bringingCar: true,
      noOfCars: "8",
      bringingSUV: true,
      noOfSUV: "5",
      bringingTruck: true,
      noOfTrucks: "1",
      brandOfTruck: "Any",
      trailersAttached: true,
      trailerLength: "5ft",
      bringingFloats: true,
      floatsLength: "4ft",
      isThereFireExtinguisher: "Yes",
      bringingAnimals: true,
      bringingHorses: true,
      areHorsesInsured: true,
      noOfHorses: "5",
      bringingDogs: true,
      noOfDogs: "4",
      anyOtherAnimal: true,
      anyOtherAnimalNoAndDescription: "Pigion, 5",
    },
    {
      id: 3,
      name: "John Sane",
      email: "john@rclister.com",
      acceptedDate: "10 oct 2022",
      applicationDate: "2022",
      approved: false,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      orgName: "ABC",
      groupPresident: "RFT",
      phone: "909090",
      representingCountry: true,
      countryName: "INDIA",
      haveWalkers: true,
      noOfWalkers: "5",
      bringingCar: true,
      noOfCars: "8",
      bringingSUV: true,
      noOfSUV: "5",
      bringingTruck: true,
      noOfTrucks: "1",
      brandOfTruck: "Any",
      trailersAttached: true,
      trailerLength: "5ft",
      bringingFloats: true,
      floatsLength: "4ft",
      isThereFireExtinguisher: "Yes",
      bringingAnimals: true,
      bringingHorses: true,
      areHorsesInsured: true,
      noOfHorses: "5",
      bringingDogs: true,
      noOfDogs: "4",
      anyOtherAnimal: true,
      anyOtherAnimalNoAndDescription: "Pigion, 5",
    },
    {
      id: 4,
      name: "John Sane",
      email: "john@rclister.com",
      acceptedDate: "10 oct 2022",
      applicationDate: "2021",
      approved: true,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      orgName: "ABC",
      groupPresident: "RFT",
      phone: "909090",
      representingCountry: true,
      countryName: "INDIA",
      haveWalkers: true,
      noOfWalkers: "5",
      bringingCar: true,
      noOfCars: "8",
      bringingSUV: true,
      noOfSUV: "5",
      bringingTruck: true,
      noOfTrucks: "1",
      brandOfTruck: "Any",
      trailersAttached: true,
      trailerLength: "5ft",
      bringingFloats: true,
      floatsLength: "4ft",
      isThereFireExtinguisher: "Yes",
      bringingAnimals: true,
      bringingHorses: true,
      areHorsesInsured: true,
      noOfHorses: "5",
      bringingDogs: true,
      noOfDogs: "4",
      anyOtherAnimal: true,
      anyOtherAnimalNoAndDescription: "Pigion, 5",
    },
    {
      id: 5,
      name: "John Sane",
      email: "john@rclister.com",
      acceptedDate: "10 oct 2020",
      applicationDate: "2020",
      approved: true,
      messageBody:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries",
      orgName: "ABC",
      groupPresident: "RFT",
      phone: "909090",
      representingCountry: true,
      countryName: "INDIA",
      haveWalkers: true,
      noOfWalkers: "5",
      bringingCar: true,
      noOfCars: "8",
      bringingSUV: true,
      noOfSUV: "5",
      bringingTruck: true,
      noOfTrucks: "1",
      brandOfTruck: "Any",
      trailersAttached: true,
      trailerLength: "5ft",
      bringingFloats: true,
      floatsLength: "4ft",
      isThereFireExtinguisher: "Yes",
      bringingAnimals: true,
      bringingHorses: true,
      areHorsesInsured: true,
      noOfHorses: "5",
      bringingDogs: true,
      noOfDogs: "4",
      anyOtherAnimal: true,
      anyOtherAnimalNoAndDescription: "Pigion, 5",
    },
  ],
};
export default allEmails;
