import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import About from "../components/About";
import Event from "../components/Event";
import Hero from "../components/Hero";
import Sponsors from "../components/Sponsors";
import en from "../locales/en";
import fr from "../locales/fr";

export default function Home() {
  const router = useRouter();
  const { locale } = router;

  const t = locale === "en-US" ? en : fr;
  return (
    <div>
      <Head>
        <title>Montreal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title={t.hero.title}
        subtitle={t.hero.subtitle}
        image="/hero.png"
        alt={t.hero.title}
        btnText={t.hero.btn}
        btn={true}
      />
      <Event />
      <About />
      <Sponsors />
    </div>
  );
}
